### Configurações Iniciais (Variáveis)
@baseUrl = http://localhost:3000
@contentType = application/json

#### 0. login de um Usuário (Testa autenticação e geração de token JWT)
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "joao@gmail.com",
  "senha": "@Senha_123"
}

###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvYW9AZ21haWwuY29tIiwic3ViIjoiY21xdm9qbGJjMDAwMG44b3l5c3dhOTJldyIsInVzZXJuYW1lIjoiSm_Do28gU2lsdmEiLCJwZXNzb2FJZCI6bnVsbCwiaWF0IjoxNzgyNTc0Mjg4LCJleHAiOjE3ODI1Nzc4ODh9.uAdwW_UVjaZ6pNzbOYnr1V6HOKant2Els-rBX4ILbDA

### 1. Criar um novo Usuário (Testa as validações do DTO)
POST {{baseUrl}}/usuario
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "username": "João Silva",
  "email": "joao@gmail.com",
  "senha": "@Senha_123"
}

###  2. Listar todos os Usuários (Testa paginação e busca)
GET {{baseUrl}}/usuario?page=1&limit=10&search=João
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

#### 3. Deletar um Usuário pelo ID
DELETE {{baseUrl}}/usuario/cmqvj2fvi000065mk2y89xv0h
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

