### Configurações Iniciais (Variáveis)
@baseUrl = http://localhost:3000
@contentType = application/json

#### 0. login de um Usuário (Testa autenticação e geração de token JWT)
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "superadmin@opticaflow.local",
  "senha": "SuperAdmin@123"
}

###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1cGVyYWRtaW5Ab3B0aWNhZmxvdy5sb2NhbCIsInN1YiI6ImNtcjJvZjB6MzAwOWhlbnNia3hhcXJsZmoiLCJ1c2VybmFtZSI6InN1cGVyYWRtaW4iLCJwZXNzb2FJZCI6bnVsbCwiaWF0IjoxNzgzMDAzMzc1LCJleHAiOjE3ODMwMDQyNzV9.4vZVUrbqSTfbPCRGHQleT5t_f0bn2CF8VLA30Z36Sqk

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbXIyb2YwejMwMDloZW5zYmt4YXFybGZqIiwidHlwZSI6InJlZnJlc2giLCJpYXQiOjE3ODMwMDQ5OTMsImV4cCI6MTc4MzYwOTc5M30.eLG0Cu4Hbm4Csr1GcfiK3got39xNGym_tQldi9m7V-w
### 1. Criar um novo Usuário (Testa as validações do DTO)
POST {{baseUrl}}/usuario
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "username": "João Silva",
  "email": "admin@opticaflow.com",
  "senha": "@admin_123"
}

###  2. Listar todos os Usuários (Testa paginação e busca)
GET {{baseUrl}}/usuario?page=1&limit=10&search=
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

#### 3. Deletar um Usuário pelo ID
DELETE {{baseUrl}}/usuario/cmr2nevif00009osb6k85nlvi
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

#### 4. refresh token JWT
POST {{baseUrl}}/auth/refresh
Content-Type: {{contentType}}

{
  "refresh_token": "{{refreshToken}}"
}